apiVersion: v1
kind: Secret
metadata:
  name: uav-store-secrets
  namespace: uav-store
type: Opaque
data:
  user-db-password:
  product-db-password:
  order-db-password:
  payment-db-password:
  minio-root-user:
  minio-root-password:
  jwt-secret:
  payos-client-id:
  payos-api-key:
  payos-checksum-key:
